Use reservoir sampling for context events
DataDog/async-profiler pull request #56
Opened 2022-03-23 17:47 UTC by jbachorik

2022-03-23 18:01 UTC, luhenry requested changes

2022-03-23 18:10 UTC, jbachorik commented on src/sampler.cpp
> +        _reservoir.push_back(elem);
I am a bit rusty on the validity scopes but I experienced a bunch of SIGSEGV when I was storing the instances directly.
My explanation was that when I instantiated the event in the calling function and the then the instance went out of scope it got destroyed. Actually, I think line 6 is not necessary and it is the remnant of my various attempts to store values in the vector.

BTW, how is it with the lifecycle of something instantiated as `ContextIntervalEvent event(....)` in function `func1()`? AFAIK, it should be destroyed the moment the function returns, correct?

2022-03-23 18:23 UTC, jbachorik commented on src/flightRecorder.cpp
> +        if (len > MAX_STRING_LENGTH) len = MAX_STRING_LENGTH;
Ok. Removed.

2022-03-24 10:43 UTC, luhenry commented on src/sampler.cpp
> +        _reservoir.push_back(elem);
> BTW, how is it with the lifecycle of something instantiated as ContextIntervalEvent event(....) in function func1()? AFAIK, it should be destroyed the moment the function returns, correct?

The object is allocated on the stack and will be freed (the destructor called) when exiting the block.

> I am a bit rusty on the validity scopes but I experienced a bunch of SIGSEGV when I was storing the instances directly.

I'm strongly suspecting problem with the lifecycle of the `_context` string. To avoid copying it all around while still guaranteeing it will be freed, I would use a `shared_ptr`. We would only have to make sure that this won't pull in the C++ stdlib.

2022-03-25 14:05 UTC, jbachorik commented on src/sampler.cpp
> +        _reservoir.push_back(elem);
Marking as resolved - @luhenry provided the fix and it has been merged here

2022-03-25 14:13 UTC, luhenry approved these changes

2022-03-25 14:20 UTC, merged