Merge tag 'v2.8.3'
DataDog/async-profiler pull request #66
Opened 2022-07-18 13:49 UTC by jbachorik

2022-07-18 16:26 UTC, luhenry requested changes

2022-07-18 16:26 UTC, luhenry commented on src/flightRecorder.cpp
> +                    buf->putVar32(0);
Is that on purpose?

2022-07-19 07:28 UTC, jbachorik commented on src/flightRecorder.cpp
> +                    buf->putVar32(0);
Nope. Apparently, the VS Code conflict resolution UI sucks and blows at the same time.
I definitely clicked to keep that change :/
Putting back ...

2022-07-19 07:37 UTC, jbachorik commented on src/profiler.cpp
> +    UNKNOWN_JAVA  = 0x1,
Yep. Reverted.

2022-07-19 08:47 UTC, luhenry approved these changes

2022-07-19 08:53 UTC, merged