introduce reservoir sampling thread selection
DataDog/async-profiler pull request #73
Opened 2022-09-27 16:07 UTC by richardstartin

2022-09-29 08:41 UTC, jbachorik requested changes
Please, take a look at the `sample_idle_threads` related code changes

2022-09-29 08:41 UTC, jbachorik commented on src/wallClock.cpp
> +            int num_threads = thread_list->size();
I think we will have to keep the logic around `sample_idle_threads` and if that's set to `false` we should skip threads which are not running in the thread list.
I don't think we are actively using the wallclock timer to drive CPU profiling in Datadog, though. However, the upstream might so if we want, possibly, to upstream this we should keep that functionality.

2022-09-29 08:41 UTC, jbachorik commented on src/wallClock.cpp
> +ThreadState WallClock::getThreadState(void *ucontext) {
Are you using an automatic code formatter?
Until now we were trying to stick to the upstream format - while it may have its own issues it kept the possibility of upstreaming the changes without an extensive reformat open for us.

2022-09-29 08:59 UTC, richardstartin commented on src/wallClock.cpp
> +ThreadState WallClock::getThreadState(void *ucontext) {
I am, let me try to revert these changes.

2022-09-29 09:05 UTC, richardstartin commented on src/wallClock.cpp
> +    WallClock* engine;
The problem is the code style is kind of inconsistent anyway, see here

2022-09-29 09:08 UTC, jbachorik commented on src/wallClock.cpp
> +    WallClock* engine;
:(
Let's see. Perhaps we could add an automated formatting step in upstream and then stick to it also in our fork?
What formatting tool are you using?

2022-09-29 10:09 UTC, richardstartin commented on src/wallClock.cpp
> +    WallClock* engine;
yes let's try that

2022-09-29 10:09 UTC, richardstartin commented on datadog/scripts/build_locally.sh
> -(cd ${HERE}/../maven/tmp/target && find $(pwd) -name '*.jar' | xargs -I {} echo "*  file://{}")
reverting this change would be a pain IDE wise, can we settle on newlines at ends of files?

2022-09-29 10:13 UTC, richardstartin commented on src/wallClock.cpp
> +            int num_threads = thread_list->size();
I believe I have addressed this concern now - `shouldSample` is evaluated before letting a thread into the reservoir. There is no guarantee the thread will still be active by the time the signal is sent but we can improve the likelihood by implementing [Vitter's algorithm D](https://www.cs.umd.edu/~samir/498/vitter.pdf) which would allow us to emit the signal as soon as we choose a thread. This doesn't feel very important right now though.

2022-09-29 10:21 UTC, jbachorik approved these changes

2022-09-29 11:40 UTC, jbachorik commented on src/wallClock.cpp
> +    WallClock* engine;
:(

2022-09-29 11:50 UTC, merged

2022-10-13 15:49 UTC, nsavoire reviewed
Very interesting code, I did not know about,algorithm L to do reservoir sampling !
Sorry for the late review, but better late than never...

2022-10-13 15:49 UTC, nsavoire commented on src/wallClock.cpp
> +                for (int i = _reservoir_size, skip = 0; i < num_threads; i += skip) {
Loop stop condition should probably be `thead_list->next() == -1`.

2022-10-13 15:49 UTC, nsavoire commented on src/wallClock.cpp
> +                    }
Since `thread_list` needs to be fully iterated over, it could perhaps be beneficial to store all threads in `reservoir`  and them randomly choosing `_reservoir_size` elements in it:
``` c++
reservoir.clear();
thread_list->rewind();
for(int thread_id = thread_list->next(); thread_id != -1; thread_id = thread_list->next()) {
    reservoir.push_back(thread_id);
}
size_t n = reservoir.size();
for(int i=0;i<_reservoir_size && n>0;++i) {
    std::uniform_int_distribution<int> random_index(0, n-1);
    int j = random_index(generator);
    while (!shouldSample(self, reservoir[j], sample_idle_threads, thread_filter_enabled, thread_filter)) {
        // Remove thread from candidates
        reservoir[j] = reservoir[n-1];
        --n;
        if (j==n) {
            if (n > 0) {
                // wrap up to the start of candidates
                j = 0;
            } else {
                break;
            }
        }
    }
    if (j!=n) {
        OS::sendSignalToThread(reservoir[j], sample_idle_threads ? SIGVTALRM : SIGPROF);
        reservoir[j] = reservoir[n-1];                    
        --n;
    }
}
```
The need to check `shouldSample` complicates things, the check could be done during the initial fill of `reservoir` but this might be undesirable since check is costly (`OS::threadState` reads `/proc/self/task/<tid>/stat`).

2022-10-13 17:21 UTC, richardstartin commented on src/wallClock.cpp
> +    std::uniform_int_distribution<int> random_index(0, _reservoir_size);
Good catch!